# Generated by Django 4.1.3 on 2022-11-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Card name', max_length=255)),
                ('version', models.IntegerField(help_text='Card_version autofill')),
                ('stats', models.JSONField(default='{"Powers": {"enter": 0, "rejection": 0, "permanent": 0, "exit": 0}, "Work": {"enter": 0, "permanent": 0, "exit": 0}, "Health": {"enter": 0, "permanent": 0, "exit": 0}, "Finances": {"enter": 0, "permanent": 0, "exit": 0}, "Relations": {"enter": 0, "permanent": 0, "exit": 0}, "Self time": {"enter": 0, "permanent": 0, "exit": 0}, "Self development": {"enter": 0, "permanent": 0, "exit": 0}, "Random enter event": "Script", "Enter condition": "Script", "Exit condition": "Script", "Rotation condition": "Script", "Additional cards": 0, "ROT_Powers": {"enter": 0, "rejection": 0, "permanent": 0, "exit": 0}, "ROT_Work": {"enter": 0, "permanent": 0, "exit": 0}, "ROT_Health": {"enter": 0, "permanent": 0, "exit": 0}, "ROT_Finances": {"enter": 0, "permanent": 0, "exit": 0}, "ROT_Relations": {"enter": 0, "permanent": 0, "exit": 0}, "ROT_Self time": {"enter": 0, "permanent": 0, "exit": 0}, "ROT_Self development": {"enter": 0, "permanent": 0, "exit": 0}, "ROT_Random enter event": "Script", "ROT_Enter condition": "Script", "ROT_Exit condition": "Script", "ROT_Rotation condition": "Script", "ROT_Additional cards": 0}', help_text='Card stats')),
                ('image', models.ImageField(blank=True, height_field=890, help_text='Image of card', upload_to='', width_field=570)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name deck', max_length=255)),
                ('version', models.IntegerField(help_text='version of deck')),
                ('cards', models.ManyToManyField(to='game.card')),
            ],
        ),
    ]
